[build]
  command = "bun run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_YARN = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle redirects for SPA navigation
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable CORS for font files
[[headers]]
  for = "/fonts/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

# Cache optimization
[[headers]]
  for = "/_next/static/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle images from remote sources
[images]
  remote_images = ["https://ext.same-assets.com/*"]
